#!/bin/bash
srun python3 Train_CDF.py -index 0 
srun python3 Train_CDF.py -index 1 
srun python3 Train_CDF.py -index 2 
srun python3 Train_CDF.py -index 3 
srun python3 Train_CDF.py -index 4 
srun python3 Train_CDF.py -index 5 
srun python3 Train_CDF.py -index 6 
srun python3 Train_CDF.py -index 7 
srun python3 Train_CDF.py -index 8 
srun python3 Train_CDF.py -index 9 
srun python3 Train_CDF.py -index 10 
srun python3 Train_CDF.py -index 11 
srun python3 Train_CDF.py -index 12 
srun python3 Train_CDF.py -index 13 
srun python3 Train_CDF.py -index 14 
srun python3 Train_CDF.py -index 15 
srun python3 Train_CDF.py -index 16 
srun python3 Train_CDF.py -index 17 
srun python3 Train_CDF.py -index 18 
srun python3 Train_CDF.py -index 19 
srun python3 Train_CDF.py -index 20 
srun python3 Train_CDF.py -index 21 
srun python3 Train_CDF.py -index 22 
srun python3 Train_CDF.py -index 23 
srun python3 Train_CDF.py -index 24 
srun python3 Train_CDF.py -index 25 
srun python3 Train_CDF.py -index 26 
srun python3 Train_CDF.py -index 27 
srun python3 Train_CDF.py -index 28 
srun python3 Train_CDF.py -index 29 
srun python3 Train_CDF.py -index 30 
srun python3 Train_CDF.py -index 31 
srun python3 Train_CDF.py -index 32 
srun python3 Train_CDF.py -index 33 
srun python3 Train_CDF.py -index 34 
srun python3 Train_CDF.py -index 35 
srun python3 Train_CDF.py -index 36 
srun python3 Train_CDF.py -index 37 
srun python3 Train_CDF.py -index 38 
srun python3 Train_CDF.py -index 39 
srun python3 Train_CDF.py -index 40 
srun python3 Train_CDF.py -index 41 
srun python3 Train_CDF.py -index 42 
srun python3 Train_CDF.py -index 43 
srun python3 Train_CDF.py -index 44 
srun python3 Train_CDF.py -index 45 
srun python3 Train_CDF.py -index 46 
srun python3 Train_CDF.py -index 47 
srun python3 Train_CDF.py -index 48 
srun python3 Train_CDF.py -index 49 
srun python3 Train_CDF.py -index 50 
srun python3 Train_CDF.py -index 51 
srun python3 Train_CDF.py -index 52 
srun python3 Train_CDF.py -index 53 
srun python3 Train_CDF.py -index 54 
srun python3 Train_CDF.py -index 55 
srun python3 Train_CDF.py -index 56 
srun python3 Train_CDF.py -index 57 
srun python3 Train_CDF.py -index 58 
srun python3 Train_CDF.py -index 59 
srun python3 Train_CDF.py -index 60 
srun python3 Train_CDF.py -index 61 
srun python3 Train_CDF.py -index 62 
srun python3 Train_CDF.py -index 63 
srun python3 Train_CDF.py -index 64 
srun python3 Train_CDF.py -index 65 
srun python3 Train_CDF.py -index 66 
srun python3 Train_CDF.py -index 67 
srun python3 Train_CDF.py -index 68 
srun python3 Train_CDF.py -index 69 
srun python3 Train_CDF.py -index 70 
srun python3 Train_CDF.py -index 71 
srun python3 Train_CDF.py -index 72 
srun python3 Train_CDF.py -index 73 
srun python3 Train_CDF.py -index 74 
srun python3 Train_CDF.py -index 75 
srun python3 Train_CDF.py -index 76 
srun python3 Train_CDF.py -index 77 
srun python3 Train_CDF.py -index 78 
srun python3 Train_CDF.py -index 79 
srun python3 Train_CDF.py -index 80 
srun python3 Train_CDF.py -index 81 
srun python3 Train_CDF.py -index 82 
srun python3 Train_CDF.py -index 83 
srun python3 Train_CDF.py -index 84 
srun python3 Train_CDF.py -index 85 
srun python3 Train_CDF.py -index 86 
srun python3 Train_CDF.py -index 87 
srun python3 Train_CDF.py -index 88 
srun python3 Train_CDF.py -index 89 
srun python3 Train_CDF.py -index 90 
srun python3 Train_CDF.py -index 91 
srun python3 Train_CDF.py -index 92 
srun python3 Train_CDF.py -index 93 
srun python3 Train_CDF.py -index 94 
srun python3 Train_CDF.py -index 95 
srun python3 Train_CDF.py -index 96 
srun python3 Train_CDF.py -index 97 
srun python3 Train_CDF.py -index 98 
srun python3 Train_CDF.py -index 99 
srun python3 Train_CDF.py -index 100 
srun python3 Train_CDF.py -index 101 
srun python3 Train_CDF.py -index 102 
srun python3 Train_CDF.py -index 103 
srun python3 Train_CDF.py -index 104 
srun python3 Train_CDF.py -index 105 
srun python3 Train_CDF.py -index 106 
srun python3 Train_CDF.py -index 107 
srun python3 Train_CDF.py -index 108 
srun python3 Train_CDF.py -index 109 
srun python3 Train_CDF.py -index 110 
srun python3 Train_CDF.py -index 111 
srun python3 Train_CDF.py -index 112 
srun python3 Train_CDF.py -index 113 
srun python3 Train_CDF.py -index 114 
srun python3 Train_CDF.py -index 115 
srun python3 Train_CDF.py -index 116 
srun python3 Train_CDF.py -index 117 
srun python3 Train_CDF.py -index 118 
srun python3 Train_CDF.py -index 119 
srun python3 Train_CDF.py -index 120 
srun python3 Train_CDF.py -index 121 
srun python3 Train_CDF.py -index 122 
srun python3 Train_CDF.py -index 123 
srun python3 Train_CDF.py -index 124 
srun python3 Train_CDF.py -index 125 
srun python3 Train_CDF.py -index 126 
srun python3 Train_CDF.py -index 127 
srun python3 Train_CDF.py -index 128 
srun python3 Train_CDF.py -index 129 
srun python3 Train_CDF.py -index 130 
srun python3 Train_CDF.py -index 131 
srun python3 Train_CDF.py -index 132 
srun python3 Train_CDF.py -index 133 
srun python3 Train_CDF.py -index 134 
srun python3 Train_CDF.py -index 135 
srun python3 Train_CDF.py -index 136 
srun python3 Train_CDF.py -index 137 
srun python3 Train_CDF.py -index 138 
srun python3 Train_CDF.py -index 139 
srun python3 Train_CDF.py -index 140 
srun python3 Train_CDF.py -index 141 
srun python3 Train_CDF.py -index 142 
srun python3 Train_CDF.py -index 143 
srun python3 Train_CDF.py -index 144 
srun python3 Train_CDF.py -index 145 
srun python3 Train_CDF.py -index 146 
srun python3 Train_CDF.py -index 147 
srun python3 Train_CDF.py -index 148 
srun python3 Train_CDF.py -index 149 
srun python3 Train_CDF.py -index 150 
srun python3 Train_CDF.py -index 151 
srun python3 Train_CDF.py -index 152 
srun python3 Train_CDF.py -index 153 
srun python3 Train_CDF.py -index 154 
srun python3 Train_CDF.py -index 155 
srun python3 Train_CDF.py -index 156 
srun python3 Train_CDF.py -index 157 
srun python3 Train_CDF.py -index 158 
srun python3 Train_CDF.py -index 159 
srun python3 Train_CDF.py -index 160 
srun python3 Train_CDF.py -index 161 
srun python3 Train_CDF.py -index 162 
srun python3 Train_CDF.py -index 163 
srun python3 Train_CDF.py -index 164 
srun python3 Train_CDF.py -index 165 
srun python3 Train_CDF.py -index 166 
srun python3 Train_CDF.py -index 167 
srun python3 Train_CDF.py -index 168 
srun python3 Train_CDF.py -index 169 
srun python3 Train_CDF.py -index 170 
srun python3 Train_CDF.py -index 171 
srun python3 Train_CDF.py -index 172 
srun python3 Train_CDF.py -index 173 
srun python3 Train_CDF.py -index 174 
srun python3 Train_CDF.py -index 175 
srun python3 Train_CDF.py -index 176 
srun python3 Train_CDF.py -index 177 
srun python3 Train_CDF.py -index 178 
srun python3 Train_CDF.py -index 179 
srun python3 Train_CDF.py -index 180 
srun python3 Train_CDF.py -index 181 
srun python3 Train_CDF.py -index 182 
srun python3 Train_CDF.py -index 183 
srun python3 Train_CDF.py -index 184 
srun python3 Train_CDF.py -index 185 
srun python3 Train_CDF.py -index 186 
srun python3 Train_CDF.py -index 187 
srun python3 Train_CDF.py -index 188 
srun python3 Train_CDF.py -index 189 
srun python3 Train_CDF.py -index 190 
srun python3 Train_CDF.py -index 191 
srun python3 Train_CDF.py -index 192 
srun python3 Train_CDF.py -index 193 
srun python3 Train_CDF.py -index 194 
srun python3 Train_CDF.py -index 195 
srun python3 Train_CDF.py -index 196 
srun python3 Train_CDF.py -index 197 
srun python3 Train_CDF.py -index 198 
srun python3 Train_CDF.py -index 199 
srun python3 Train_CDF.py -index 200 
srun python3 Train_CDF.py -index 201 
srun python3 Train_CDF.py -index 202 
srun python3 Train_CDF.py -index 203 
srun python3 Train_CDF.py -index 204 
srun python3 Train_CDF.py -index 205 
srun python3 Train_CDF.py -index 206 
srun python3 Train_CDF.py -index 207 
srun python3 Train_CDF.py -index 208 
srun python3 Train_CDF.py -index 209 
srun python3 Train_CDF.py -index 210 
srun python3 Train_CDF.py -index 211 
srun python3 Train_CDF.py -index 212 
srun python3 Train_CDF.py -index 213 
srun python3 Train_CDF.py -index 214 
srun python3 Train_CDF.py -index 215 
srun python3 Train_CDF.py -index 216 
srun python3 Train_CDF.py -index 217 
srun python3 Train_CDF.py -index 218 
srun python3 Train_CDF.py -index 219 
srun python3 Train_CDF.py -index 220 
srun python3 Train_CDF.py -index 221 
srun python3 Train_CDF.py -index 222 
srun python3 Train_CDF.py -index 223 
srun python3 Train_CDF.py -index 224 
srun python3 Train_CDF.py -index 225 
srun python3 Train_CDF.py -index 226 
srun python3 Train_CDF.py -index 227 
srun python3 Train_CDF.py -index 228 
srun python3 Train_CDF.py -index 229 
srun python3 Train_CDF.py -index 230 
srun python3 Train_CDF.py -index 231 
srun python3 Train_CDF.py -index 232 
srun python3 Train_CDF.py -index 233 
srun python3 Train_CDF.py -index 234 
srun python3 Train_CDF.py -index 235 
srun python3 Train_CDF.py -index 236 
srun python3 Train_CDF.py -index 237 
srun python3 Train_CDF.py -index 238 
srun python3 Train_CDF.py -index 239 
srun python3 Train_CDF.py -index 240 
srun python3 Train_CDF.py -index 241 
srun python3 Train_CDF.py -index 242 
srun python3 Train_CDF.py -index 243 
srun python3 Train_CDF.py -index 244 
srun python3 Train_CDF.py -index 245 
srun python3 Train_CDF.py -index 246 
srun python3 Train_CDF.py -index 247 
srun python3 Train_CDF.py -index 248 
srun python3 Train_CDF.py -index 249 
srun python3 Train_CDF.py -index 250 
srun python3 Train_CDF.py -index 251 
srun python3 Train_CDF.py -index 252 
srun python3 Train_CDF.py -index 253 
srun python3 Train_CDF.py -index 254 
srun python3 Train_CDF.py -index 255 
srun python3 Train_CDF.py -index 256 
srun python3 Train_CDF.py -index 257 
srun python3 Train_CDF.py -index 258 
srun python3 Train_CDF.py -index 259 
srun python3 Train_CDF.py -index 260 
srun python3 Train_CDF.py -index 261 
srun python3 Train_CDF.py -index 262 
srun python3 Train_CDF.py -index 263 
srun python3 Train_CDF.py -index 264 
srun python3 Train_CDF.py -index 265 
srun python3 Train_CDF.py -index 266 
srun python3 Train_CDF.py -index 267 
srun python3 Train_CDF.py -index 268 
srun python3 Train_CDF.py -index 269 
srun python3 Train_CDF.py -index 270 
srun python3 Train_CDF.py -index 271 
srun python3 Train_CDF.py -index 272 
srun python3 Train_CDF.py -index 273 
srun python3 Train_CDF.py -index 274 
srun python3 Train_CDF.py -index 275 
srun python3 Train_CDF.py -index 276 
srun python3 Train_CDF.py -index 277 
srun python3 Train_CDF.py -index 278 
srun python3 Train_CDF.py -index 279 
srun python3 Train_CDF.py -index 280 
srun python3 Train_CDF.py -index 281 
srun python3 Train_CDF.py -index 282 
srun python3 Train_CDF.py -index 283 
srun python3 Train_CDF.py -index 284 
srun python3 Train_CDF.py -index 285 
srun python3 Train_CDF.py -index 286 
srun python3 Train_CDF.py -index 287 
srun python3 Train_CDF.py -index 288 
srun python3 Train_CDF.py -index 289 
srun python3 Train_CDF.py -index 290 
srun python3 Train_CDF.py -index 291 
srun python3 Train_CDF.py -index 292 
srun python3 Train_CDF.py -index 293 
srun python3 Train_CDF.py -index 294 
srun python3 Train_CDF.py -index 295 
srun python3 Train_CDF.py -index 296 
srun python3 Train_CDF.py -index 297 
srun python3 Train_CDF.py -index 298 
srun python3 Train_CDF.py -index 299 
srun python3 Train_CDF.py -index 300 
srun python3 Train_CDF.py -index 301 
srun python3 Train_CDF.py -index 302 
srun python3 Train_CDF.py -index 303 
srun python3 Train_CDF.py -index 304 
srun python3 Train_CDF.py -index 305 
srun python3 Train_CDF.py -index 306 
srun python3 Train_CDF.py -index 307 
srun python3 Train_CDF.py -index 308 
srun python3 Train_CDF.py -index 309 
srun python3 Train_CDF.py -index 310 
srun python3 Train_CDF.py -index 311 
srun python3 Train_CDF.py -index 312 
srun python3 Train_CDF.py -index 313 
srun python3 Train_CDF.py -index 314 
srun python3 Train_CDF.py -index 315 
srun python3 Train_CDF.py -index 316 
srun python3 Train_CDF.py -index 317 
srun python3 Train_CDF.py -index 318 
srun python3 Train_CDF.py -index 319 
srun python3 Train_CDF.py -index 320 
srun python3 Train_CDF.py -index 321 
srun python3 Train_CDF.py -index 322 
srun python3 Train_CDF.py -index 323 
srun python3 Train_CDF.py -index 324 
srun python3 Train_CDF.py -index 325 
srun python3 Train_CDF.py -index 326 
srun python3 Train_CDF.py -index 327 
srun python3 Train_CDF.py -index 328 
srun python3 Train_CDF.py -index 329 
srun python3 Train_CDF.py -index 330 
srun python3 Train_CDF.py -index 331 
srun python3 Train_CDF.py -index 332 
srun python3 Train_CDF.py -index 333 
srun python3 Train_CDF.py -index 334 
srun python3 Train_CDF.py -index 335 
srun python3 Train_CDF.py -index 336 
srun python3 Train_CDF.py -index 337 
srun python3 Train_CDF.py -index 338 
srun python3 Train_CDF.py -index 339 
srun python3 Train_CDF.py -index 340 
srun python3 Train_CDF.py -index 341 
srun python3 Train_CDF.py -index 342 
srun python3 Train_CDF.py -index 343 
srun python3 Train_CDF.py -index 344 
srun python3 Train_CDF.py -index 345 
srun python3 Train_CDF.py -index 346 
srun python3 Train_CDF.py -index 347 
srun python3 Train_CDF.py -index 348 
srun python3 Train_CDF.py -index 349 
srun python3 Train_CDF.py -index 350 
srun python3 Train_CDF.py -index 351 
srun python3 Train_CDF.py -index 352 
srun python3 Train_CDF.py -index 353 
srun python3 Train_CDF.py -index 354 
srun python3 Train_CDF.py -index 355 
srun python3 Train_CDF.py -index 356 
srun python3 Train_CDF.py -index 357 
srun python3 Train_CDF.py -index 358 
srun python3 Train_CDF.py -index 359 
srun python3 Train_CDF.py -index 360 
srun python3 Train_CDF.py -index 361 
srun python3 Train_CDF.py -index 362 
srun python3 Train_CDF.py -index 363 
srun python3 Train_CDF.py -index 364 
srun python3 Train_CDF.py -index 365 
srun python3 Train_CDF.py -index 366 
srun python3 Train_CDF.py -index 367 
srun python3 Train_CDF.py -index 368 
srun python3 Train_CDF.py -index 369 
srun python3 Train_CDF.py -index 370 
srun python3 Train_CDF.py -index 371 
srun python3 Train_CDF.py -index 372 
srun python3 Train_CDF.py -index 373 
srun python3 Train_CDF.py -index 374 
srun python3 Train_CDF.py -index 375 
srun python3 Train_CDF.py -index 376 
srun python3 Train_CDF.py -index 377 
srun python3 Train_CDF.py -index 378 
srun python3 Train_CDF.py -index 379 
srun python3 Train_CDF.py -index 380 
srun python3 Train_CDF.py -index 381 
srun python3 Train_CDF.py -index 382 
srun python3 Train_CDF.py -index 383 
srun python3 Train_CDF.py -index 384 
srun python3 Train_CDF.py -index 385 
srun python3 Train_CDF.py -index 386 
srun python3 Train_CDF.py -index 387 
srun python3 Train_CDF.py -index 388 
srun python3 Train_CDF.py -index 389 
srun python3 Train_CDF.py -index 390 
srun python3 Train_CDF.py -index 391 
srun python3 Train_CDF.py -index 392 
srun python3 Train_CDF.py -index 393 
srun python3 Train_CDF.py -index 394 
srun python3 Train_CDF.py -index 395 
srun python3 Train_CDF.py -index 396 
srun python3 Train_CDF.py -index 397 
srun python3 Train_CDF.py -index 398 
srun python3 Train_CDF.py -index 399 
